/** 牌桌域字典（table./action./panel./result./tour. 前缀）——由牌桌 UI 组维护 */
export const TABLE_DICT = {
  // ---- table.* 牌桌通用 ----
  "table.rotateHint": {
    zh: "9 人桌在竖屏较拥挤，旋转屏幕获得最佳体验",
    en: "9-max is cramped in portrait — rotate your device for the best experience",
  },
  "table.dismissHint": { zh: "关闭提示", en: "Dismiss" },
  "table.folded": { zh: "已弃牌", en: "Folded" },
  "table.starting": { zh: "正在开局…", en: "Starting…" },
  "table.opening": { zh: "开局中…", en: "Starting…" },
  "table.cardBack": { zh: "牌背面", en: "Card back" },
  // 牌桌中央街道标签（短式，区别于 dict-core street.* 的「圈」长名）
  "table.street.preflop": { zh: "翻前", en: "Preflop" },
  "table.street.flop": { zh: "翻牌", en: "Flop" },
  "table.street.turn": { zh: "转牌", en: "Turn" },
  "table.street.river": { zh: "河牌", en: "River" },
  "table.street.showdown": { zh: "摊牌", en: "Showdown" },
  "table.tournamentBlind": {
    zh: "锦标赛 {seats} 人 · Lv.{level}",
    en: "Tournament · {seats} players · Lv.{level}",
  },
  "table.cashBlind": {
    zh: "盲注 {sb}/{bb} · {seats} 人",
    en: "Blinds {sb}/{bb} · {seats} players",
  },
  "table.handNumber": { zh: "第 {n} 手", en: "Hand #{n}" },
  "table.soundOn": { zh: "开启音效", en: "Unmute sound" },
  "table.soundOff": { zh: "关闭音效", en: "Mute sound" },
  "table.soundStateOn": { zh: "音效：开", en: "Sound: on" },
  "table.soundStateOff": { zh: "音效：关", en: "Sound: off" },
  "table.dismissError": { zh: "关闭错误提示", en: "Dismiss error" },

  // ---- action.* 行动栏（基础动作词在 dict-core，此处为牌桌专属补充） ----
  "action.betTo": { zh: "下注到", en: "Bet to" },
  "action.raiseTo": { zh: "加注到", en: "Raise to" },
  "action.betAmount": { zh: "下注金额", en: "Bet amount" },
  "action.halfPot": { zh: "½ 池", en: "½ pot" },
  "action.threeQuarterPot": { zh: "¾ 池", en: "¾ pot" },
  "action.allInAmount": { zh: "全下 {n}", en: "All-in {n}" },
  "action.aiThinking": { zh: "AI 思考中…", en: "AI thinking…" },
  "action.waitingOpponents": { zh: "等待对手行动…", en: "Waiting for opponents…" },
  "action.preActionLabel": { zh: "预操作：", en: "Pre-action:" },
  "action.hotkeys": {
    zh: "快捷键：F 弃牌 · C 过牌/跟注 · B 加注滑杆 · Enter 确认",
    en: "Hotkeys: F Fold · C Check/Call · B Raise slider · Enter Confirm",
  },

  // ---- panel.* 信息面板 ----
  "panel.expand": { zh: "展开信息面板", en: "Expand info panel" },
  "panel.collapse": { zh: "收起信息面板", en: "Collapse info panel" },
  "panel.equity": { zh: "胜率", en: "Equity" },
  "panel.odds": { zh: "赔率", en: "Odds" },
  "panel.equityTitle": { zh: "胜率提示", en: "Equity" },
  "panel.winLabel": { zh: "胜", en: "Win" },
  "panel.tieLabel": { zh: "平", en: "Tie" },
  "panel.loseLabel": { zh: "负", en: "Loss" },
  "panel.equityEmpty": {
    zh: "开局后显示胜率",
    en: "Equity appears once the hand starts",
  },
  "panel.potOdds": { zh: "底池赔率", en: "Pot Odds" },
  "panel.needCall": { zh: "需跟注 {n}", en: "Call {n} needed" },
  "panel.noCallNeeded": { zh: "当前无需跟注", en: "No call needed right now" },
  "panel.aiTitle": { zh: "AI 动态", en: "AI Activity" },
  "panel.lastAction": { zh: "上一动作（{name}）：", en: "Last action ({name}): " },
  "panel.aiReasoningLlm": { zh: "AI 思考（LLM）", en: "AI reasoning (LLM)" },
  "panel.aiReasoningHeuristic": {
    zh: "决策说明（启发式）",
    en: "Decision notes (heuristic)",
  },
  "panel.aiIdle": { zh: "AI 尚未行动", en: "No AI action yet" },
  "panel.session": { zh: "本会话", en: "Session" },
  "panel.hands": { zh: "手数", en: "Hands" },
  "panel.wins": { zh: "胜场", en: "Wins" },
  "panel.heuristic": { zh: "启发式", en: "Heuristic" },
  "panel.sourceLlm": { zh: "由大模型生成", en: "Generated by an LLM" },
  "panel.sourceHeuristic": {
    zh: "由本地启发式生成（LLM 未启用或已回退）",
    en: "Generated by the local heuristic (LLM disabled or fallen back)",
  },

  // ---- result.* 结算（基础词在 dict-core，此处为牌桌专属补充） ----
  "result.spectatingPlace": {
    zh: "你已获得第 {place} 名 · 观战中… AI 正在打完剩余牌局",
    en: "Finished #{place} · Spectating… AI is playing out the remaining hands",
  },
  "result.spectating": {
    zh: "观战中… AI 正在打完剩余牌局",
    en: "Spectating… AI is playing out the remaining hands",
  },
  "result.pause": { zh: "暂停", en: "Pause" },
  "result.resume": { zh: "继续", en: "Resume" },
  "result.backToLobby": { zh: "返回大厅", en: "Back to Lobby" },
  "result.bustRebuyLeft": {
    zh: "筹码归零 · 剩余重购 {n} 次",
    en: "Busted · {n} rebuys left",
  },
  "result.concedeNote": {
    zh: "认输将以第 {place} 名离场观战",
    en: "Concede to finish #{place} and spectate",
  },
  "result.rebuyContinue": {
    zh: "重购继续（买回 {n}）",
    en: "Rebuy for {n} and continue",
  },
  "result.concedeSpectate": { zh: "认输观战", en: "Concede & Spectate" },
  "result.busted": { zh: "筹码归零", en: "Busted" },
  "result.belowBb": {
    zh: "筹码不足大盲（剩 {n}）",
    en: "Stack below the big blind ({n} left)",
  },
  "result.resetBuyin": { zh: "重置买入（{n}）", en: "Reset buy-in ({n})" },
  "result.leaveSpectate": { zh: "下桌观战", en: "Leave & Spectate" },
  "result.youAreChampion": { zh: "🏆 你是冠军！", en: "🏆 You are the Champion!" },
  "result.tournamentOver": { zh: "锦标赛结束", en: "Tournament Over" },
  "result.winnersLabel": { zh: "胜者：", en: "Winner: " },
  "result.bustPlace": {
    zh: "{name} 获得第 {place} 名",
    en: "{name} finished #{place}",
  },
  "result.championIs": { zh: "冠军：{name}", en: "Champion: {name}" },
  "result.yourFinalPlace": {
    zh: "你的最终名次：第 {place} 名",
    en: "Your final place: #{place}",
  },
  "result.noShowdown": {
    zh: "其余玩家弃牌，未摊牌",
    en: "Everyone else folded — no showdown",
  },

  // ---- tour.* 锦标赛 ----
  "tour.level": { zh: "级别 Lv.{level}", en: "Level {level}" },
  "tour.blinds": { zh: "盲注 {sb}/{bb}", en: "Blinds {sb}/{bb}" },
  "tour.toLevelUp": { zh: "距升级还剩", en: "Next level in" },
  "tour.handsSuffix": { zh: "手", en: "hands" },
  "tour.remaining": { zh: "剩余", en: "Remaining" },
  "tour.playersSuffix": { zh: "人", en: "players" },
  "tour.youChampion": { zh: "🏆 你是冠军", en: "🏆 You are the Champion" },
  "tour.endedPlace": {
    zh: "已结束 · 你第 {place} 名",
    en: "Over · You finished #{place}",
  },
  "tour.eliminatedPlace": {
    zh: "你已出局 · 第 {place} 名",
    en: "Eliminated · Finished #{place}",
  },
  "tour.goal": {
    zh: "目标：夺冠（当前最差并列第 {n}）",
    en: "Goal: win the title (worst case: tied #{n})",
  },
  "tour.levelUp": { zh: "盲注升级！", en: "Blinds Up!" },
  "tour.rebuyHint": {
    zh: "重购期内（前 {n} 级）筹码归零可买回起始筹码",
    en: "During the rebuy period (first {n} levels), busting lets you buy back the starting stack",
  },
  "tour.rebuyDisabled": { zh: "重购已停用", en: "Rebuys disabled" },
  "tour.rebuysLeft": { zh: "剩余重购 {n} 次", en: "{n} rebuys left" },
} as const;
